name: dbt-test
on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Triggered on each pull request to main
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-bookworm

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./transform/dbt/requirements.txt

      - name: Install dbt packages
        run: dbt deps
        working-directory: ./transform/dbt/ecommerce_etl
        
      - name: Run dbt tests
        env:
          DEV_CLICKHOUSE_HOST: ${{ secrets.DEV_CLICKHOUSE_HOST }}
          DEV_CLICKHOUSE_DATABASE: ${{ secrets.DEV_CLICKHOUSE_DATABASE }}
          DEV_CLICKHOUSE_USERNAME: ${{ secrets.DEV_CLICKHOUSE_USERNAME }}
          DEV_CLICKHOUSE_PASSWORD: ${{ secrets.DEV_CLICKHOUSE_PASSWORD }}
        run: dbt test
        working-directory: ./transform/dbt/ecommerce_etl
